"""
inthon.memory.sqlite_store — Persistent, searchable memory backend for INTHON agents.

Replaces the volatile InMemoryStore with a SQLite database that survives
process restarts. Supports both keyword search (always available) and
vector cosine-similarity search (when the embedder is active).

Schema:
    memory_entries(id, namespace, content_text, value_json, embedding, created_at, updated_at, tags)

The embedding column stores a raw float32 array as BLOB, generated by
inthon.memory.embedder. On search, the top-K entries by cosine similarity
are returned in ranked order.
"""

from __future__ import annotations

import json
import sqlite3
import struct
import time
from pathlib import Path
from typing import Any

from .store import MemoryStore, MemoryEntry


class SQLiteMemoryStore(MemoryStore):
    """
    Persistent, searchable memory store backed by SQLite.

    Attributes:
        db_path: Path to the SQLite database file.
        use_embeddings: Whether to generate and store vector embeddings.
            Requires `sentence-transformers` or falls back to trigram vectors.
    """

    # Embedding dimension placeholder — updated on first embed call
    _SCHEMA = """
    CREATE TABLE IF NOT EXISTS memory_entries (
        id          TEXT NOT NULL,
        namespace   TEXT NOT NULL DEFAULT 'session',
        content_text TEXT NOT NULL,
        value_json  TEXT NOT NULL,
        embedding   BLOB,
        created_at  REAL NOT NULL,
        updated_at  REAL NOT NULL,
        tags        TEXT NOT NULL DEFAULT '',
        PRIMARY KEY (id, namespace)
    );
    CREATE INDEX IF NOT EXISTS idx_ns ON memory_entries(namespace);
    CREATE INDEX IF NOT EXISTS idx_updated ON memory_entries(updated_at);
    """

    def __init__(
        self,
        db_path: str | Path = ":memory:",
        use_embeddings: bool = True,
    ) -> None:
        self._db_path = str(db_path)
        self._use_embeddings = use_embeddings
        self._conn: sqlite3.Connection = sqlite3.connect(
            self._db_path,
            check_same_thread=False,  # Safe for single-threaded VM; async VM uses its own conn
        )
        self._conn.row_factory = sqlite3.Row
        self._conn.execute("PRAGMA journal_mode=WAL;")  # Better write concurrency
        self._conn.execute("PRAGMA synchronous=NORMAL;")
        self._conn.executescript(self._SCHEMA)
        self._conn.commit()

        # Lazy embedder init
        self._embedder = None
        if use_embeddings:
            try:
                from .embedder import get_embedder

                self._embedder = get_embedder()
            except Exception:
                self._embedder = None

    # ── MemoryStore interface ─────────────────────────────────────────── #

    def write(self, key: str, value: Any, namespace: str = "session") -> MemoryEntry:
        now = time.time()
        content_text = self._to_text(value)
        value_json = json.dumps(value, default=str)

        embedding_blob = self._encode_embedding(content_text)

        existing = self._conn.execute(
            "SELECT id, created_at FROM memory_entries WHERE id=? AND namespace=?",
            (key, namespace),
        ).fetchone()

        if existing:
            self._conn.execute(
                """UPDATE memory_entries
                   SET content_text=?, value_json=?, embedding=?, updated_at=?, tags=''
                   WHERE id=? AND namespace=?""",
                (content_text, value_json, embedding_blob, now, key, namespace),
            )
        else:
            self._conn.execute(
                """INSERT INTO memory_entries
                   (id, namespace, content_text, value_json, embedding, created_at, updated_at, tags)
                   VALUES (?,?,?,?,?,?,?,'')""",
                (key, namespace, content_text, value_json, embedding_blob, now, now),
            )
        self._conn.commit()

        return MemoryEntry(
            key=key,
            value=value,
            namespace=namespace,
            created_at=now,
            updated_at=now,
        )

    def read(self, key: str, namespace: str = "session") -> MemoryEntry | None:
        row = self._conn.execute(
            "SELECT * FROM memory_entries WHERE id=? AND namespace=?",
            (key, namespace),
        ).fetchone()
        if row is None:
            return None
        return self._row_to_entry(row)

    def delete(self, key: str, namespace: str = "session") -> bool:
        cursor = self._conn.execute(
            "DELETE FROM memory_entries WHERE id=? AND namespace=?",
            (key, namespace),
        )
        self._conn.commit()
        return cursor.rowcount > 0

    def search(
        self,
        query: str,
        namespace: str = "session",
        limit: int = 10,
    ) -> list[MemoryEntry]:
        """
        Semantic search using cosine similarity (if embeddings available)
        or keyword substring match as fallback.
        """
        if self._embedder is not None:
            return self._vector_search(query, namespace, limit)
        return self._keyword_search(query, namespace, limit)

    # ── Search implementations ────────────────────────────────────────── #

    def _keyword_search(
        self, query: str, namespace: str, limit: int
    ) -> list[MemoryEntry]:
        rows = self._conn.execute(
            """SELECT * FROM memory_entries
               WHERE namespace=? AND content_text LIKE ?
               ORDER BY updated_at DESC LIMIT ?""",
            (namespace, f"%{query}%", limit),
        ).fetchall()
        return [self._row_to_entry(r) for r in rows]

    def _vector_search(
        self, query: str, namespace: str, limit: int
    ) -> list[MemoryEntry]:
        """Ranked cosine similarity search over stored embeddings."""
        query_vec = self._embedder.embed(query)

        # Fetch all rows in namespace that have embeddings
        rows = self._conn.execute(
            "SELECT * FROM memory_entries WHERE namespace=? AND embedding IS NOT NULL",
            (namespace,),
        ).fetchall()

        # Fallback to keyword if no embeddings in namespace
        if not rows:
            return self._keyword_search(query, namespace, limit)

        scored: list[tuple[float, MemoryEntry]] = []
        for row in rows:
            emb = self._decode_embedding(row["embedding"])
            if emb:
                from .embedder import LocalEmbedder

                score = LocalEmbedder.cosine_similarity(query_vec, emb)
                scored.append((score, self._row_to_entry(row)))

        # Also include entries without embeddings via keyword
        no_emb_rows = self._conn.execute(
            """SELECT * FROM memory_entries
               WHERE namespace=? AND embedding IS NULL AND content_text LIKE ?""",
            (namespace, f"%{query}%"),
        ).fetchall()
        for row in no_emb_rows:
            scored.append((0.5, self._row_to_entry(row)))  # Mid-rank for keyword hits

        scored.sort(key=lambda x: x[0], reverse=True)
        return [entry for _, entry in scored[:limit]]

    # ── Embedding serialisation ───────────────────────────────────────── #

    def _encode_embedding(self, text: str) -> bytes | None:
        if self._embedder is None:
            return None
        try:
            vec = self._embedder.embed(text)
            return struct.pack(f"{len(vec)}f", *vec)
        except Exception:
            return None

    def _decode_embedding(self, blob: bytes | None) -> list[float] | None:
        if blob is None:
            return None
        try:
            n = len(blob) // 4  # 4 bytes per float32
            return list(struct.unpack(f"{n}f", blob))
        except Exception:
            return None

    # ── Helpers ───────────────────────────────────────────────────────── #

    @staticmethod
    def _to_text(value: Any) -> str:
        """Convert any value to a searchable text representation."""
        if isinstance(value, str):
            return value
        return json.dumps(value, default=str)

    def _row_to_entry(self, row: sqlite3.Row) -> MemoryEntry:
        try:
            value = json.loads(row["value_json"])
        except (json.JSONDecodeError, TypeError):
            value = row["value_json"]
        return MemoryEntry(
            key=row["id"],
            value=value,
            namespace=row["namespace"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            tags=row["tags"].split(",") if row["tags"] else [],
        )

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()

    def __del__(self) -> None:
        try:
            self._conn.close()
        except Exception:
            pass

    # ── Statistics ────────────────────────────────────────────────────── #

    def stats(self, namespace: str | None = None) -> dict:
        """Return memory store statistics."""
        if namespace:
            row = self._conn.execute(
                "SELECT COUNT(*) as n FROM memory_entries WHERE namespace=?",
                (namespace,),
            ).fetchone()
        else:
            row = self._conn.execute(
                "SELECT COUNT(*) as n FROM memory_entries"
            ).fetchone()
        return {
            "total_entries": row["n"],
            "db_path": self._db_path,
            "embeddings_enabled": self._embedder is not None,
            "using_ml_embeddings": self._embedder.using_ml if self._embedder else False,
        }
