"""
inthon.runtime.dryrun — Declarative DryRun Mocking engine for INTHON tools.

Generates synthetic data conforming to declared tool output schemas.
"""

from __future__ import annotations
from typing import Any


def mock_type_value(type_str: str) -> Any:
    """Generate a mock value of a given type string."""
    type_str = type_str.strip().lower()
    if type_str == "str":
        return "mock_str_content"
    elif type_str in ("int", "integer"):
        return 42
    elif type_str in ("float", "double"):
        return 3.14
    elif type_str == "bool":
        return True
    elif type_str == "list[dict]":
        return [
            {
                "title": "Mock Search Result",
                "url": "https://mock.example.com",
                "snippet": "This is a mock search snippet generated by INTHON DryRun engine.",
            }
        ]
    elif type_str == "list[str]":
        return ["mock_item_1", "mock_item_2"]
    elif type_str.startswith("list"):
        return ["mock_list_item"]
    elif type_str == "dict":
        return {"mock_key": "mock_value"}
    return None


def generate_mock_output(output_schema: dict[str, str] | None) -> dict[str, Any]:
    """Generate a dictionary conforming to the specified output schema."""
    if not output_schema:
        return {}
    res = {}
    for name, type_str in output_schema.items():
        res[name] = mock_type_value(type_str)
    return res
