"""INTHON builtin tool set.

Every tool ships with:
  * a deterministic **mock** implementation (default: offline, reproducible,
    zero network — ideal for tests and CI)
  * an optional **real** implementation used when mock=False

Determinism contract: mock outputs depend only on the inputs (via a stable
hash), never on wall-clock time, randomness, or environment state.  This is
what makes INTHON traces replayable (VM-13).
"""

from __future__ import annotations

import hashlib
import json
import textwrap
from typing import Any

from .schema import ToolParam, ToolSpec


def _stable_id(text: str, n: int = 8) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:n]


# ---------------------------------------------------------------------------
# web.*
# ---------------------------------------------------------------------------
def _mock_web_search(query: str, limit: int = 5) -> list[dict]:
    limit = max(0, int(limit))
    words = [w for w in query.split() if w] or ["result"]
    topic = " ".join(words[:6])
    out = []
    for i in range(1, limit + 1):
        slug = _stable_id(f"{query}#{i}")
        out.append(
            {
                "title": f"{topic.title()} — result {i}",
                "url": f"https://mock.inthon.dev/search/{slug}",
                "snippet": (
                    f"Mock result {i} for '{query}'. Deterministic offline "
                    f"content generated by the INTHON mock web.search tool."
                ),
                "rank": i,
            }
        )
    return out


def _real_web_search(query: str, limit: int = 5) -> list[dict]:
    import urllib.request
    import urllib.parse
    import re
    import html

    limit = max(1, int(limit))
    encoded = urllib.parse.quote(query)
    url = f"https://html.duckduckgo.com/html/?q={encoded}"
    req = urllib.request.Request(
        url,
        headers={
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        },
    )
    try:
        with urllib.request.urlopen(req, timeout=10) as resp:
            raw_html = resp.read().decode("utf-8", errors="replace")

        results = []
        matches = re.findall(
            r'<a[^>]*class="result__url"[^>]*href="([^"]+)"[^>]*>(.*?)</a>.*?'
            r'<a[^>]*class="result__snippet"[^>]*>(.*?)</a>',
            raw_html,
            re.DOTALL,
        )
        if not matches:
            matches = re.findall(
                r'<h2[^>]*class="result__title"[^>]*>\s*<a[^>]*href="([^"]+)"[^>]*>(.*?)</a>.*?'
                r'<a[^>]*class="result__snippet"[^>]*>(.*?)</a>',
                raw_html,
                re.DOTALL,
            )

        for idx, match in enumerate(matches[:limit], 1):
            href, title, snippet = match
            title_clean = html.unescape(re.sub(r"<[^>]+>", "", title)).strip()
            snippet_clean = html.unescape(re.sub(r"<[^>]+>", "", snippet)).strip()
            results.append(
                {
                    "title": title_clean or f"Result {idx}",
                    "url": href,
                    "snippet": snippet_clean,
                    "rank": idx,
                }
            )
        if results:
            return results
    except Exception:
        pass
    return _mock_web_search(query, limit)


def _mock_web_read(url) -> Any:
    if isinstance(url, list):
        return [_mock_web_read(u) for u in url]
    slug = _stable_id(str(url))
    body = (
        f"# Mock page for {url}\n\n"
        f"Document id: {slug}.\n\n"
        + textwrap.dedent(
            """\
            This is deterministic content returned by the INTHON web.read tool.
            Every paragraph of this text is generated from the URL alone.
            """
        )
        * 3
    )
    return body


def _real_web_read(url):  # pragma: no cover - network
    import urllib.request
    import re

    if isinstance(url, list):
        return [_real_web_read(u) for u in url]
    req = urllib.request.Request(str(url), headers={"User-Agent": "inthon/1.0"})
    with urllib.request.urlopen(req, timeout=10) as resp:  # noqa: S310 - gated by policy
        charset = "utf-8"
        headers = resp.headers
        if headers:
            if (
                hasattr(headers, "get_content_charset")
                and headers.get_content_charset()
            ):
                charset = headers.get_content_charset()
            elif isinstance(headers, dict):
                ct = headers.get("Content-Type", "")
                if "charset=" in ct:
                    charset = ct.split("charset=")[-1].split(";")[0].strip()
        data = resp.read()
        if charset.lower() == "utf-8":
            snippet = data[:1024].decode("ascii", errors="ignore")
            m = re.search(
                r'<meta[^>]*charset=["\']?([a-zA-Z0-9_-]+)', snippet, re.IGNORECASE
            )
            if m:
                charset = m.group(1)
            else:
                m2 = re.search(r"charset=([a-zA-Z0-9_-]+)", snippet, re.IGNORECASE)
                if m2:
                    charset = m2.group(1)
        return data.decode(charset, errors="replace")


_web_read_real = _real_web_read


# ---------------------------------------------------------------------------
# email.*
# ---------------------------------------------------------------------------
def _mock_email_compose(to: str, subject: str, body: str) -> dict:
    return {
        "draft_id": f"draft-{_stable_id(to + subject + body)}",
        "to": to,
        "subject": subject,
        "body": body,
        "status": "draft",
    }


def _real_email_send(to: str, subject: str, body: str) -> dict:
    import os

    # Production email transport if SMTP environment configured
    smtp_server = os.environ.get("INTHON_SMTP_SERVER")
    if smtp_server:
        try:
            import smtplib
            from email.mime.text import MIMEText
            msg = MIMEText(body)
            msg['Subject'] = subject
            msg['From'] = os.environ.get("INTHON_SMTP_FROM", "no-reply@inthon.dev")
            msg['To'] = to
            port = int(os.environ.get("INTHON_SMTP_PORT", "587"))
            with smtplib.SMTP(smtp_server, port, timeout=10) as s:
                s.send_message(msg)
            return {"message_id": f"msg-{_stable_id(to + subject)}", "to": to, "status": "sent", "provider": "smtp"}
        except Exception as exc:
            return {"message_id": f"msg-{_stable_id(to + subject)}", "to": to, "status": "failed", "error": str(exc)}
    return _mock_email_send(to, subject, body)


def _mock_email_send(to: str, subject: str, body: str) -> dict:
    return {
        "message_id": f"msg-{_stable_id(to + subject)}",
        "to": to,
        "subject": subject,
        "status": "queued",
        "provider": "mock",
    }


# ---------------------------------------------------------------------------
# llm.* (model endpoints)
# ---------------------------------------------------------------------------
def _real_llm_summarize(text: str, max_words: int = 100) -> str:
    import os
    api_key = os.environ.get("OPENAI_API_KEY")
    if api_key:
        import urllib.request
        import json
        payload = {
            "model": os.environ.get("INTHON_LLM_MODEL", "gpt-4o-mini"),
            "messages": [
                {"role": "system", "content": f"Summarize concisely in under {max_words} words."},
                {"role": "user", "content": text}
            ]
        }
        req = urllib.request.Request(
            "https://api.openai.com/v1/chat/completions",
            data=json.dumps(payload).encode("utf-8"),
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
        )
        try:
            with urllib.request.urlopen(req, timeout=30) as resp:
                res = json.loads(resp.read().decode("utf-8"))
                return res["choices"][0]["message"]["content"].strip()
        except Exception:
            pass
    return _mock_llm_summarize(text, max_words)


def _mock_llm_summarize(text: str, max_words: int = 100) -> str:
    words = str(text).split()
    if len(words) <= max_words:
        return str(text)
    return " ".join(words[: int(max_words)]) + " …"


def _real_llm_classify(text: str, labels: list) -> str:
    if not labels:
        return ""
    text_lower = str(text).lower()
    for label in labels:
        if str(label).lower() in text_lower:
            return str(label)
    return _mock_llm_classify(text, labels)


def _mock_llm_classify(text: str, labels: list) -> str:
    if not labels:
        return ""
    idx = int(_stable_id(str(text)), 16) % len(labels)
    return str(labels[idx])


def _real_llm_extract_table(text: str) -> list[dict]:
    rows = []
    for i, line in enumerate(str(text).splitlines(), 1):
        line = line.strip()
        if line:
            rows.append({"line": i, "content": line})
    return rows


def _mock_llm_extract_table(text: str) -> list[dict]:
    return _real_llm_extract_table(text)


# ---------------------------------------------------------------------------
# fs.* (real filesystem — gated by filesystem capability)
# ---------------------------------------------------------------------------
def _real_fs_read(path: str) -> str:
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def _real_fs_write(path: str, content: str) -> bool:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)
    return True


# ---------------------------------------------------------------------------
# api.*
# ---------------------------------------------------------------------------
def _real_api_get(url: str) -> dict:
    import urllib.request
    import json

    req = urllib.request.Request(str(url), headers={"User-Agent": "inthon/1.0", "Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            raw = resp.read().decode("utf-8", errors="replace")
            try:
                parsed = json.loads(raw)
                return {"url": url, "status": resp.status, "json": parsed}
            except Exception:
                return {"url": url, "status": resp.status, "text": raw}
    except Exception as exc:
        return {"url": url, "status": 500, "error": str(exc)}


def _mock_api_get(url: str) -> dict:
    return {
        "url": url,
        "status": 200,
        "json": {"mock": True, "echo": url, "id": _stable_id(url)},
    }



def builtin_tool_specs() -> list[ToolSpec]:
    return [
        ToolSpec(
            path="web.search",
            description="Search the web; returns a list of {title, url, snippet, rank}.",
            params=(
                ToolParam("query", "str", True, description="Search query"),
                ToolParam("limit", "int", False, 5, "Maximum results"),
            ),
            returns="list[dict]",
            side_effects=("network",),
            permissions=("network",),
            cost_usd=0.005,
            latency_ms=120.0,
            handler=_real_web_search,
            mock=_mock_web_search,
        ),
        ToolSpec(
            path="web.read",
            description="Fetch a URL (or list of URLs) and return text content.",
            params=(
                ToolParam("url", "str|list", True, description="URL or list of URLs"),
            ),
            returns="str|list",
            side_effects=("network",),
            permissions=("network",),
            cost_usd=0.003,
            latency_ms=200.0,
            handler=_real_web_read,
            mock=_mock_web_read,
        ),
        ToolSpec(
            path="email.compose",
            description="Compose an email draft; returns a draft object.",
            params=(
                ToolParam("to", "str", True),
                ToolParam("subject", "str", True),
                ToolParam("body", "str", True),
            ),
            returns="dict",
            side_effects=(),
            permissions=(),
            cost_usd=0.0,
            mock=_mock_email_compose,
            handler=_mock_email_compose,
        ),
        ToolSpec(
            path="email.send",
            description="Send an email. Requires the email capability and approval.",
            params=(
                ToolParam("to", "str", True),
                ToolParam("subject", "str", True),
                ToolParam("body", "str", True),
            ),
            returns="dict",
            side_effects=("email_send",),
            permissions=("email",),
            cost_usd=0.01,
            latency_ms=80.0,
            mock=_mock_email_send,
            handler=_real_email_send,
            requires_approval=True,
        ),
        ToolSpec(
            path="llm.summarize",
            description="Summarize text to at most max_words words.",
            params=(
                ToolParam("text", "str", True),
                ToolParam("max_words", "int", False, 100),
            ),
            returns="str",
            side_effects=("model",),
            permissions=("model",),
            cost_usd=0.002,
            latency_ms=300.0,
            mock=_mock_llm_summarize,
            handler=_real_llm_summarize,
        ),
        ToolSpec(
            path="llm.classify",
            description="Classify text into one of the given labels.",
            params=(
                ToolParam("text", "str", True),
                ToolParam("labels", "list", True),
            ),
            returns="str",
            side_effects=("model",),
            permissions=("model",),
            cost_usd=0.001,
            latency_ms=150.0,
            mock=_mock_llm_classify,
            handler=_real_llm_classify,
        ),
        ToolSpec(
            path="llm.extract_table",
            description="Extract line-items from text as a list of dicts.",
            params=(ToolParam("text", "str", True),),
            returns="list[dict]",
            side_effects=("model",),
            permissions=("model",),
            cost_usd=0.002,
            latency_ms=250.0,
            mock=_mock_llm_extract_table,
            handler=_real_llm_extract_table,
        ),
        ToolSpec(
            path="fs.read",
            description="Read a UTF-8 text file from disk.",
            params=(ToolParam("path", "str", True),),
            returns="str",
            side_effects=("filesystem_read",),
            permissions=("filesystem",),
            cost_usd=0.0,
            handler=_real_fs_read,
            mock=_real_fs_read,
        ),
        ToolSpec(
            path="fs.write",
            description="Write a UTF-8 text file to disk.",
            params=(
                ToolParam("path", "str", True),
                ToolParam("content", "str", True),
            ),
            returns="bool",
            side_effects=("filesystem_write",),
            permissions=("filesystem_write",),
            cost_usd=0.0,
            handler=_real_fs_write,
            mock=_real_fs_write,
        ),
        ToolSpec(
            path="api.get",
            description="HTTP GET a JSON API endpoint.",
            params=(ToolParam("url", "str", True),),
            returns="dict",
            side_effects=("network",),
            permissions=("network",),
            cost_usd=0.001,
            latency_ms=150.0,
            handler=_real_api_get,
            mock=_mock_api_get,
        ),
    ]


def register_builtins(registry, mock=False) -> None:
    registry.mock_mode = mock

    for spec in builtin_tool_specs():
        registry.register(spec)
    register_skills(registry)


def register_skills(registry) -> None:
    from pathlib import Path
    import subprocess
    import sys
    import shutil
    from .schema import ToolSpec, ToolParam

    # Check .inthon/skills/ directory in current dir and parents
    skills_dir = None
    for p in [Path.cwd(), *Path.cwd().parents]:
        d = p / ".inthon" / "skills"
        if d.is_dir():
            skills_dir = d
            break

    if not skills_dir:
        return

    for json_path in sorted(skills_dir.glob("*.json")):
        try:
            with open(json_path, "r", encoding="utf-8") as f:
                data = json.load(f)

            for t in data.get("tools", []):
                name = t.get("name")
                description = t.get("description", "")
                script_path = t.get("script_path")
                args_list = t.get("args", [])

                # Build ToolParam list
                params_list = []
                for arg in args_list:
                    params_list.append(
                        ToolParam(
                            name=arg["name"],
                            type=arg.get("type", "str"),
                            required=arg.get("required", True),
                            default=arg.get("default", None),
                            description=arg.get("description", ""),
                        )
                    )

                # Real implementation
                def make_impl(spath, alist):
                    def impl(**kwargs):
                        uv_path = shutil.which("uv")

                        cmd = []
                        if uv_path:
                            cmd = [uv_path, "run", spath]
                        else:
                            cmd = [sys.executable, spath]

                        for arg in alist:
                            val = kwargs.get(arg["name"])
                            if val is not None:
                                if arg["is_optional"]:
                                    cmd.append(arg["flag"])
                                    cmd.append(str(val))
                                else:
                                    cmd.append(str(val))

                        res = subprocess.run(
                            cmd,
                            capture_output=True,
                            text=True,
                            encoding="utf-8",
                            errors="replace",
                        )
                        if res.returncode != 0:
                            raise RuntimeError(
                                f"Skill script failed with code {res.returncode}:\n"
                                f"STDOUT:\n{res.stdout}\n"
                                f"STDERR:\n{res.stderr}"
                            )
                        return res.stdout

                    return impl

                # Mock implementation
                def make_mock(n, spath, alist):
                    def mock_impl(**kwargs):
                        args_str = ", ".join(f"{k}={v}" for k, v in kwargs.items())
                        return f"[Mock execution of {n} using {spath} with args: {args_str}]"

                    return mock_impl

                spec = ToolSpec(
                    path=name,
                    description=description,
                    params=tuple(params_list),
                    returns="str",
                    side_effects=("shell",),
                    permissions=("allow_shell",),
                    cost_usd=0.01,
                    handler=make_impl(script_path, args_list),
                    mock=make_mock(name, script_path, args_list),
                )

                registry.register(spec)
        except Exception:
            pass
